services:
  db:
    image: postgres:latest
    container_name: community-hub-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: community_hub_user
      POSTGRES_PASSWORD: community_hub_password
      POSTGRES_DB: community_hub
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: community-hub-frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      REACT_APP_API_URL: http://backend:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: community-hub-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://community_hub_user:community_hub_password@db:5432/community_hub
    volumes:
      - ./backend:/app
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 community_hub.wsgi"

  liquibase:
    build: ./liquibase
    container_name: community-hub-liquibase
    depends_on:
      - db
    command: update --changelog-file=changelog/1.0.0.yaml --username community_hub_user --password community_hub_password --url jdbc:postgresql://db:5432/community_hub
    volumes:
      - ./liquibase/changelog:/liquibase/changelog

volumes:
  db_data:
